language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - ./build_etcd.sh

# command to install dependencies
install: 
  - python bootstrap.py -v 2.1.1
  - bin/buildout

# command to run tests
script:
  PATH=$PATH:./etcd bin/test

# Only test main development branch and releases
branches:
  only:
    - master
    - /^release_.*$/
    - /^travis_.*$/

