language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: 
  - python bootstrap.py -v 2.1.1
  - bin/buildout

# command to run tests
script:
  bin/test etcd.tests.unit

# Only test main development branch and releases
branches:
  only:
    - master
    - /^release_.*$/
