language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - ./build_etcd.sh v0.1.2

# command to install dependencies
install: 
  - python bootstrap.py
  - bin/buildout

# command to run tests
script:
  PATH=$PATH:./etcd bin/test

# Add env var to detect it during build
env: TRAVIS=True
